CREATE SCHEMA IF NOT EXISTS tuyensinh;
SET search_path TO tuyensinh;

CREATE TABLE IF NOT EXISTS thi_sinh (
    ma_thi_sinh INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_ten VARCHAR(100) NOT NULL,
    ngay_sinh DATE,
    gioi_tinh VARCHAR(10),
    cccd VARCHAR(12) UNIQUE,
    email VARCHAR(100),
    so_dien_thoai VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS nguoi_dung (
    ma_nguoi_dung INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_ten VARCHAR(100) NOT NULL,
    ten_dang_nhap VARCHAR(50) UNIQUE NOT NULL,
    mat_khau VARCHAR(255) NOT NULL,
    vai_tro VARCHAR(30) NOT NULL DEFAULT 'CAN_BO'
);

CREATE TABLE IF NOT EXISTS ho_so (
    ma_ho_so INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_thi_sinh INTEGER NOT NULL REFERENCES thi_sinh(ma_thi_sinh)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    ma_nguoi_dung INTEGER REFERENCES nguoi_dung(ma_nguoi_dung)
        ON UPDATE CASCADE ON DELETE SET NULL,
    ngay_nop TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_XU_LY',
    qr_hash VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS loai_giay_to (
    ma_loai INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_loai VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS giay_to (
    ma_giay_to INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_ho_so INTEGER NOT NULL REFERENCES ho_so(ma_ho_so)
        ON UPDATE CASCADE ON DELETE CASCADE,
    ma_loai INTEGER NOT NULL REFERENCES loai_giay_to(ma_loai)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    ten_file VARCHAR(255) NOT NULL,
    duong_dan VARCHAR(255) NOT NULL,
    chat_luong_anh VARCHAR(50),
    ngay_tai_len TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ocr_result (
    ma_ocr INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_giay_to INTEGER NOT NULL REFERENCES giay_to(ma_giay_to)
        ON UPDATE CASCADE ON DELETE CASCADE,
    truong_du_lieu VARCHAR(100) NOT NULL,
    gia_tri TEXT,
    do_tin_cay DOUBLE PRECISION CHECK (
        do_tin_cay IS NULL OR (do_tin_cay >= 0 AND do_tin_cay <= 1)
    )
);

CREATE TABLE IF NOT EXISTS canh_bao (
    ma_canh_bao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_ho_so INTEGER NOT NULL REFERENCES ho_so(ma_ho_so)
        ON UPDATE CASCADE ON DELETE CASCADE,
    loai_loi VARCHAR(100) NOT NULL,
    mo_ta TEXT,
    muc_do VARCHAR(20) NOT NULL DEFAULT 'THAP'
        CHECK (muc_do IN ('THAP','TRUNG_BINH','CAO','NGHIEM_TRONG')),
    ngay_tao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO loai_giay_to (ten_loai) VALUES
('CCCD/CMND'),
('Học bạ/Bảng điểm'),
('Giấy chứng nhận tốt nghiệp'),
('Bằng tốt nghiệp'),
('Giấy tờ ưu tiên')
ON CONFLICT (ten_loai) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_ho_so_ma_thi_sinh ON ho_so(ma_thi_sinh);
CREATE INDEX IF NOT EXISTS idx_ho_so_trang_thai ON ho_so(trang_thai);
CREATE INDEX IF NOT EXISTS idx_giay_to_ma_ho_so ON giay_to(ma_ho_so);
CREATE INDEX IF NOT EXISTS idx_ocr_ma_giay_to ON ocr_result(ma_giay_to);
CREATE INDEX IF NOT EXISTS idx_canh_bao_ma_ho_so ON canh_bao(ma_ho_so);

CREATE OR REPLACE VIEW v_tong_quan_ho_so AS
SELECT
    hs.ma_ho_so,
    ts.ma_thi_sinh,
    ts.ho_ten,
    ts.cccd,
    ts.email,
    hs.ngay_nop,
    hs.trang_thai,
    nd.ho_ten AS can_bo_phu_trach,
    COUNT(DISTINCT gt.ma_giay_to) AS so_giay_to,
    COUNT(DISTINCT cb.ma_canh_bao) AS so_canh_bao
FROM ho_so hs
JOIN thi_sinh ts ON ts.ma_thi_sinh = hs.ma_thi_sinh
LEFT JOIN nguoi_dung nd ON nd.ma_nguoi_dung = hs.ma_nguoi_dung
LEFT JOIN giay_to gt ON gt.ma_ho_so = hs.ma_ho_so
LEFT JOIN canh_bao cb ON cb.ma_ho_so = hs.ma_ho_so
GROUP BY hs.ma_ho_so, ts.ma_thi_sinh, ts.ho_ten, ts.cccd, ts.email,
         hs.ngay_nop, hs.trang_thai, nd.ho_ten;
